name: Lint Awesome List
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: max/awesome-lint@v2.0.0
      #- name: Run ZAP OWASP full scan
       # uses: zaproxy/action-full-scan@v0.4.0
        #with:
         # docker_name: 'owasp/zap2docker-stable'
          #token: ${{ secrets.GITHUB_TOKEN }}
          #target: 'http://testphp.vulnweb.com/'
          #cmd_options: '-a -j -l WARN -z "-addoninstallall" '
          #allow_issue_writing: true
        #id: zap-scan- 
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
